In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [23]:
df = pd.read_csv("../dataset/hdfc_loan_dataset_full_enriched.csv")

In [24]:
df.head()

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Property_Area,Age,Loan_Status,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Purpose_of_Loan,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Business_Type,Asset_Value,Guarantor,Co-signer_Relationship,Monthly_Expense,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Institutional_Relationships,Application_Text,Customer_Feedback,Agent_Notes,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,8031545,360,1,Urban,36,Approved,699,683712,0.098,Home,5610,0,0,1,NaN,744861,No,Friend,30391,Public,KOL-004,No,Yes,"RBI:Regulatory, NPCI:Payments integration, CIB...",Applicant requests home loan for amount INR 80...,Neutral — application was okay; expects quicke...,Verified documents; requires guarantor for app...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,899361,240,1,Rural,42,Rejected,707,22272,4.939,Business,9166,1,0,0,NaN,0,No,Sibling,1856,Startup,DEL-001,No,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant requests business loan for amount IN...,Complained about credit score errors and wants...,Escalated to relationship manager for manual C...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,2387748,60,1,Rural,38,Approved,641,774636,0.000,Business,0,2,0,1,NaN,2913766,No,NaN,24557,Private,BLR-003,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",Applicant requests business loan for amount IN...,"Satisfied with application process, but unhapp...",Escalated to relationship manager for manual C...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,658856,12,1,Semiurban,32,Approved,677,1061400,0.301,Personal,26613,1,0,3,NaN,3488244,No,Friend,36750,Startup,KOL-004,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant mentions dispute with property valua...,Complained about credit score errors and wants...,Escalated to relationship manager for manual C...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,198671,36,0,Semiurban,35,Approved,594,114468,0.000,Personal,0,0,0,2,Agriculture,472179,No,Parent,3920,Public,BLR-003,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant mentions dispute with property valua...,Appreciative of online service and prompt comm...,Verified documents; requires guarantor for app...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper

In [25]:
df.shape

(1000, 47)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan_ID                      1000 non-null   str
 1   Bank                         1000 non-null   str
 2   Customer_Name                1000 non-null   str
 3   Gender                       1000 non-null   str
 4   Married                      1000 non-null   str
 5   Dependents                   1000 non-null   int64
 6   Education                    1000 non-null   str
 7   Employment_Status            1000 non-null   str
 8   Applicant_Income             1000 non-null   int64
 9   Coapplicant_Income           1000 non-null   int64
 10  Loan_Amount                  1000 non-null   int64
 11  Loan_Term_Months             1000 non-null   int64
 12  Credit_History               1000 non-null   int64
 13  Property_Area                1000 non-null   str
 14  Age                          1000 non-null   int64
 15  Loan_Status                  1000 non-null   str
 16  CIBIL_Score                  1000 non-null   int64
 17  Annual_Household_Income      1000 non-null   int64
 18  Debt_to_Income_Ratio         1000 non-null   float64
 19  Purpose_of_Loan              1000 non-null   str
 20  Existing_EMIs                1000 non-null   int64
 21  Number_of_Previous_Loans     1000 non-null   int64
 22  Default_History_Count        1000 non-null   int64
 23  Employment_Length_Years      1000 non-null   int64
 24  Business_Type                201 non-null    str
 25  Asset_Value                  1000 non-null   int64
 26  Guarantor                    1000 non-null   str
 27  Co-signer_Relationship       766 non-null    str
 28  Monthly_Expense              1000 non-null   int64
 29  Organization_Type            1000 non-null   str
 30  Region_Branch                1000 non-null   str
 31  Mobile_Verified              1000 non-null   str
 32  Email_Verified               1000 non-null   str
 33  Institutional_Relationships  1000 non-null   str
 34  Application_Text             1000 non-null   str
 35  Customer_Feedback            1000 non-null   str
 36  Agent_Notes                  1000 non-null   str
 37  Loan_to_Annual_Income        1000 non-null   float64
 38  Customer_Sentiment           1000 non-null   str
 39  Religion                     1000 non-null   str
 40  State                        1000 non-null   str
 41  City                         1000 non-null   str
 42  PIN_Code                     1000 non-null   int64
 43  Aadhaar_Synthetic            1000 non-null   float64
 44  Phone_Number                 1000 non-null   int64
 45  Email                        1000 non-null   str
 46  Occupation                   1000 non-null   str
dtypes: float64(3), int64(17), str(27)
memory usage: 808.5 KB

In [27]:
df.isnull().sum()

Loan_ID                          0
Bank                             0
Customer_Name                    0
Gender                           0
Married                          0
Dependents                       0
Education                        0
Employment_Status                0
Applicant_Income                 0
Coapplicant_Income               0
Loan_Amount                      0
Loan_Term_Months                 0
Credit_History                   0
Property_Area                    0
Age                              0
Loan_Status                      0
CIBIL_Score                      0
Annual_Household_Income          0
Debt_to_Income_Ratio             0
Purpose_of_Loan                  0
Existing_EMIs                    0
Number_of_Previous_Loans         0
Default_History_Count            0
Employment_Length_Years          0
Business_Type                  799
Asset_Value                      0
Guarantor                        0
Co-signer_Relationship         234
Monthly_Expense                  0
Organization_Type                0
Region_Branch                    0
Mobile_Verified                  0
Email_Verified                   0
Institutional_Relationships      0
Application_Text                 0
Customer_Feedback                0
Agent_Notes                      0
Loan_to_Annual_Income            0
Customer_Sentiment               0
Religion                         0
State                            0
City                             0
PIN_Code                         0
Aadhaar_Synthetic                0
Phone_Number                     0
Email                            0
Occupation                       0
dtype: int64

In [28]:
df.drop(columns=["Business_Type"], inplace=True)

In [29]:
df.isnull().sum()

Loan_ID                          0
Bank                             0
Customer_Name                    0
Gender                           0
Married                          0
Dependents                       0
Education                        0
Employment_Status                0
Applicant_Income                 0
Coapplicant_Income               0
Loan_Amount                      0
Loan_Term_Months                 0
Credit_History                   0
Property_Area                    0
Age                              0
Loan_Status                      0
CIBIL_Score                      0
Annual_Household_Income          0
Debt_to_Income_Ratio             0
Purpose_of_Loan                  0
Existing_EMIs                    0
Number_of_Previous_Loans         0
Default_History_Count            0
Employment_Length_Years          0
Asset_Value                      0
Guarantor                        0
Co-signer_Relationship         234
Monthly_Expense                  0
Organization_Type                0
Region_Branch                    0
Mobile_Verified                  0
Email_Verified                   0
Institutional_Relationships      0
Application_Text                 0
Customer_Feedback                0
Agent_Notes                      0
Loan_to_Annual_Income            0
Customer_Sentiment               0
Religion                         0
State                            0
City                             0
PIN_Code                         0
Aadhaar_Synthetic                0
Phone_Number                     0
Email                            0
Occupation                       0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.describe()

,Dependents,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Age,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Monthly_Expense,Loan_to_Annual_Income,PIN_Code,Aadhaar_Synthetic,Phone_Number
count,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.00000,1.000000e+03,1.000000e+03
mean,0.849000,42430.057000,9727.11400,2.216713e+06,159.132000,0.72300,34.412000,653.01300,6.258861e+05,148.118157,18173.390000,0.865000,0.147000,2.434000,1.908042e+06,23603.427000,10.163103,509976.40800,4.853217e+11,9.500193e+09
std,0.964951,28133.210769,20568.25945,2.635021e+06,127.056704,0.44774,8.572616,73.83654,4.724545e+05,1974.599103,16298.460525,0.911925,0.499641,2.791673,1.481451e+06,18054.598235,25.415631,289145.26265,2.925311e+11,2.875105e+08
min,0.000000,0.000000,0.00000,1.884000e+03,12.000000,0.00000,18.000000,384.00000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.003000,622.00000,2.589553e+08,9.002443e+09
25%,0.000000,18260.000000,0.00000,3.729465e+05,36.000000,0.00000,28.000000,605.75000,2.639520e+05,0.031000,1741.750000,0.000000,0.000000,0.000000,7.424400e+05,9159.250000,0.645750,263067.50000,2.190000e+11,9.254018e+09
50%,1.000000,40675.500000,0.00000,9.720460e+05,120.000000,1.00000,35.000000,654.00000,5.512440e+05,0.332000,16289.500000,1.000000,0.000000,2.000000,1.634312e+06,20787.500000,2.309000,517643.50000,4.735000e+11,9.498140e+09
75%,2.000000,61037.250000,7956.50000,3.315038e+06,300.000000,1.00000,40.000000,704.00000,8.565480e+05,0.795000,29718.500000,1.000000,0.000000,3.000000,2.726302e+06,33067.750000,8.326750,756922.00000,7.300000e+11,9.750462e+09
max,3.000000,149266.000000,123461.00000,1.379096e+07,360.000000,1.00000,66.000000,878.00000,2.555340e+06,38342.000000,82436.000000,5.000000,3.000000,15.000000,7.742001e+06,97762.000000,269.754000,998910.00000,9.990000e+11,9.999102e+09

In [32]:
df.columns.tolist()

['Loan_ID',
 'Bank',
 'Customer_Name',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Employment_Status',
 'Applicant_Income',
 'Coapplicant_Income',
 'Loan_Amount',
 'Loan_Term_Months',
 'Credit_History',
 'Property_Area',
 'Age',
 'Loan_Status',
 'CIBIL_Score',
 'Annual_Household_Income',
 'Debt_to_Income_Ratio',
 'Purpose_of_Loan',
 'Existing_EMIs',
 'Number_of_Previous_Loans',
 'Default_History_Count',
 'Employment_Length_Years',
 'Asset_Value',
 'Guarantor',
 'Co-signer_Relationship',
 'Monthly_Expense',
 'Organization_Type',
 'Region_Branch',
 'Mobile_Verified',
 'Email_Verified',
 'Institutional_Relationships',
 'Application_Text',
 'Customer_Feedback',
 'Agent_Notes',
 'Loan_to_Annual_Income',
 'Customer_Sentiment',
 'Religion',
 'State',
 'City',
 'PIN_Code',
 'Aadhaar_Synthetic',
 'Phone_Number',
 'Email',
 'Occupation']

In [33]:
print("\nCategorical Summary:")
display(df.describe(include='object'))

Categorical Summary:

C:\Users\sujal\AppData\Local\Temp\ipykernel_15580\3745775991.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,Loan_ID,Bank,Customer_Name,Gender,Married,Education,Employment_Status,Property_Area,Loan_Status,Purpose_of_Loan,Guarantor,Co-signer_Relationship,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Institutional_Relationships,Application_Text,Customer_Feedback,Agent_Notes,Customer_Sentiment,Religion,State,City,Email,Occupation
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,766,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,1000,1,41,3,2,2,4,3,2,7,2,5,5,7,2,2,5,222,5,5,3,5,10,29,41,18
top,HDFC100001,HDFC Bank,Ananya Joshi,Male,Yes,Graduate,Salaried,Urban,Approved,Home,No,Spouse,Public,CHN-007,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, Government...",Applicant cites medical emergency and requests...,Appreciative of online service and prompt comm...,High risk — further KYC needed and background ...,Negative,Hindu,Tamil Nadu,Hyderabad,ananya.joshi@example.in,Small Business Owner
freq,1,1000,79,651,592,717,591,354,653,346,793,241,216,161,888,833,230,215,222,207,353,713,125,51,79,70

In [34]:
drop_cols = [
    'Bank',
    'Customer_Name',
    'Email',
    'Phone_Number',
    'Aadhaar_Synthetic',
    'PIN_Code',
    'Application_Text',
    'Customer_Feedback',
    'Agent_Notes'
]

df.drop(columns=drop_cols, inplace=True)

In [35]:
df

,Loan_ID,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Property_Area,Age,Loan_Status,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Purpose_of_Loan,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Guarantor,Co-signer_Relationship,Monthly_Expense,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Institutional_Relationships,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,Occupation
0,HDFC100001,Male,No,2,Graduate,Salaried,56976,0,8031545,360,1,Urban,36,Approved,699,683712,0.098,Home,5610,0,0,1,744861,No,Friend,30391,Public,KOL-004,No,Yes,"RBI:Regulatory, NPCI:Payments integration, CIB...",11.747,Positive,Hindu,Delhi,Dwarka,Farmer
1,HDFC100002,Male,No,0,Graduate,Unemployed,1856,0,899361,240,1,Rural,42,Rejected,707,22272,4.939,Business,9166,1,0,0,0,No,Sibling,1856,Startup,DEL-001,No,Yes,"NPCI:UPI integrations, SWIFT:International tra...",40.381,Negative,Hindu,Punjab,Ludhiana,Civil Engineer
2,HDFC100003,Female,Yes,0,Graduate,Salaried,64553,0,2387748,60,1,Rural,38,Approved,641,774636,0.000,Business,0,2,0,1,2913766,No,NaN,24557,Private,BLR-003,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",3.082,Positive,Hindu,Maharashtra,Nagpur,Medical Representative
3,HDFC100004,Male,No,0,Graduate,Salaried,88450,0,658856,12,1,Semiurban,32,Approved,677,1061400,0.301,Personal,26613,1,0,3,3488244,No,Friend,36750,Startup,KOL-004,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",0.621,Negative,Hindu,Gujarat,Vadodara,Marketing Executive
4,HDFC100005,Male,Yes,3,Graduate,Self-Employed,9539,0,198671,36,0,Semiurban,35,Approved,594,114468,0.000,Personal,0,0,0,2,472179,No,Parent,3920,Public,BLR-003,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",1.736,Neutral,Sikh,West Bengal,Kolkata,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,Male,Yes,1,Graduate,Salaried,44713,0,5883603,360,1,Urban,35,Approved,707,536556,0.116,Home,5165,1,0,2,1895538,Yes,Sibling,11899,MNC,HYD-005,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,Medical Representative
996,HDFC100997,Male,No,2,Graduate,Salaried,70886,0,2780228,300,0,Semiurban,37,Rejected,561,850632,0.284,Home,20102,1,0,1,2413969,No,Spouse,32458,MNC,KOL-004,Yes,No,"RBI:Regulatory oversight, SEBI:Market insights...",3.268,Negative,Hindu,Kerala,Trivandrum,Customer Support Executive
997,HDFC100998,Female,No,1,Graduate,Salaried,24392,11337,301249,24,1,Semiurban,28,Approved,725,428748,0.966,Education,34514,2,0,0,1631635,No,Friend,22977,Startup,PUNE-006,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",0.703,Positive,Hindu,Delhi,New Delhi,Driver
998,HDFC100999,Female,No,2,Graduate,Salaried,64803,94136,719891,48,1,Urban,33,Approved,679,1907268,0.214,Auto,34000,1,0,4,5000832,No,Parent,72376,Private,BLR-003,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",0.377,Negative,Hindu,Gujarat,Ahmedabad,Electrician
999,HDFC101000,Female,Yes,0,Graduate,Self-Employed,22938,0,61019,120,1,Rural,24,Approved,690,275256,0.664,Business,15226,0,0,0,0,Yes,Sibling,16105,Government,BLR-003,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",0.222,Neutral,Hindu,Uttar Pradesh,Noida,Marketing Executive

In [36]:
df.isnull().sum().sort_values(ascending=False)

Co-signer_Relationship         234
Gender                           0
Married                          0
Dependents                       0
Loan_ID                          0
Education                        0
Employment_Status                0
Coapplicant_Income               0
Applicant_Income                 0
Loan_Term_Months                 0
Credit_History                   0
Property_Area                    0
Loan_Amount                      0
Loan_Status                      0
CIBIL_Score                      0
Annual_Household_Income          0
Debt_to_Income_Ratio             0
Purpose_of_Loan                  0
Existing_EMIs                    0
Number_of_Previous_Loans         0
Age                              0
Default_History_Count            0
Employment_Length_Years          0
Asset_Value                      0
Guarantor                        0
Monthly_Expense                  0
Organization_Type                0
Region_Branch                    0
Mobile_Verified                  0
Email_Verified                   0
Institutional_Relationships      0
Loan_to_Annual_Income            0
Customer_Sentiment               0
Religion                         0
State                            0
City                             0
Occupation                       0
dtype: int64

In [37]:
df['Co-signer_Relationship'] = df['Co-signer_Relationship'].fillna('Unknown')

In [38]:
df.isnull().sum().sum()

np.int64(0)

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan_ID                      1000 non-null   str
 1   Gender                       1000 non-null   str
 2   Married                      1000 non-null   str
 3   Dependents                   1000 non-null   int64
 4   Education                    1000 non-null   str
 5   Employment_Status            1000 non-null   str
 6   Applicant_Income             1000 non-null   int64
 7   Coapplicant_Income           1000 non-null   int64
 8   Loan_Amount                  1000 non-null   int64
 9   Loan_Term_Months             1000 non-null   int64
 10  Credit_History               1000 non-null   int64
 11  Property_Area                1000 non-null   str
 12  Age                          1000 non-null   int64
 13  Loan_Status                  1000 non-null   str
 14  CIBIL_Score                  1000 non-null   int64
 15  Annual_Household_Income      1000 non-null   int64
 16  Debt_to_Income_Ratio         1000 non-null   float64
 17  Purpose_of_Loan              1000 non-null   str
 18  Existing_EMIs                1000 non-null   int64
 19  Number_of_Previous_Loans     1000 non-null   int64
 20  Default_History_Count        1000 non-null   int64
 21  Employment_Length_Years      1000 non-null   int64
 22  Asset_Value                  1000 non-null   int64
 23  Guarantor                    1000 non-null   str
 24  Co-signer_Relationship       1000 non-null   str
 25  Monthly_Expense              1000 non-null   int64
 26  Organization_Type            1000 non-null   str
 27  Region_Branch                1000 non-null   str
 28  Mobile_Verified              1000 non-null   str
 29  Email_Verified               1000 non-null   str
 30  Institutional_Relationships  1000 non-null   str
 31  Loan_to_Annual_Income        1000 non-null   float64
 32  Customer_Sentiment           1000 non-null   str
 33  Religion                     1000 non-null   str
 34  State                        1000 non-null   str
 35  City                         1000 non-null   str
 36  Occupation                   1000 non-null   str
dtypes: float64(2), int64(15), str(20)
memory usage: 476.0 KB

In [41]:
df.select_dtypes(include='object').columns.tolist()

C:\Users\sujal\AppData\Local\Temp\ipykernel_15580\3152244773.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns.tolist()

['Loan_ID',
 'Gender',
 'Married',
 'Education',
 'Employment_Status',
 'Property_Area',
 'Loan_Status',
 'Purpose_of_Loan',
 'Guarantor',
 'Co-signer_Relationship',
 'Organization_Type',
 'Region_Branch',
 'Mobile_Verified',
 'Email_Verified',
 'Institutional_Relationships',
 'Customer_Sentiment',
 'Religion',
 'State',
 'City',
 'Occupation']

In [42]:
loan_ids = df['Loan_ID']
df.drop(columns=['Loan_ID'], inplace=True)

In [44]:
df.shape

(1000, 36)

In [43]:
df.head()

,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Property_Area,Age,Loan_Status,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Purpose_of_Loan,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Guarantor,Co-signer_Relationship,Monthly_Expense,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Institutional_Relationships,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,Occupation
0,Male,No,2,Graduate,Salaried,56976,0,8031545,360,1,Urban,36,Approved,699,683712,0.098,Home,5610,0,0,1,744861,No,Friend,30391,Public,KOL-004,No,Yes,"RBI:Regulatory, NPCI:Payments integration, CIB...",11.747,Positive,Hindu,Delhi,Dwarka,Farmer
1,Male,No,0,Graduate,Unemployed,1856,0,899361,240,1,Rural,42,Rejected,707,22272,4.939,Business,9166,1,0,0,0,No,Sibling,1856,Startup,DEL-001,No,Yes,"NPCI:UPI integrations, SWIFT:International tra...",40.381,Negative,Hindu,Punjab,Ludhiana,Civil Engineer
2,Female,Yes,0,Graduate,Salaried,64553,0,2387748,60,1,Rural,38,Approved,641,774636,0.000,Business,0,2,0,1,2913766,No,Unknown,24557,Private,BLR-003,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",3.082,Positive,Hindu,Maharashtra,Nagpur,Medical Representative
3,Male,No,0,Graduate,Salaried,88450,0,658856,12,1,Semiurban,32,Approved,677,1061400,0.301,Personal,26613,1,0,3,3488244,No,Friend,36750,Startup,KOL-004,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",0.621,Negative,Hindu,Gujarat,Vadodara,Marketing Executive
4,Male,Yes,3,Graduate,Self-Employed,9539,0,198671,36,0,Semiurban,35,Approved,594,114468,0.000,Personal,0,0,0,2,472179,No,Parent,3920,Public,BLR-003,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",1.736,Neutral,Sikh,West Bengal,Kolkata,Shopkeeper

In [45]:
loan_ids

0      HDFC100001
1      HDFC100002
2      HDFC100003
3      HDFC100004
4      HDFC100005
          ...
995    HDFC100996
996    HDFC100997
997    HDFC100998
998    HDFC100999
999    HDFC101000
Name: Loan_ID, Length: 1000, dtype: str

In [46]:
df.nunique().sort_values(ascending=False)

Loan_Amount                    1000
Annual_Household_Income         945
Asset_Value                     935
Applicant_Income                926
Loan_to_Annual_Income           918
Monthly_Expense                 892
Existing_EMIs                   769
Debt_to_Income_Ratio            626
Coapplicant_Income              344
CIBIL_Score                     304
Age                              44
City                             29
Occupation                       18
Employment_Length_Years          16
Loan_Term_Months                 11
State                            10
Purpose_of_Loan                   7
Region_Branch                     7
Co-signer_Relationship            6
Number_of_Previous_Loans          6
Organization_Type                 5
Institutional_Relationships       5
Religion                          5
Dependents                        4
Default_History_Count             4
Employment_Status                 4
Gender                            3
Customer_Sentiment                3
Property_Area                     3
Married                           2
Education                         2
Credit_History                    2
Loan_Status                       2
Guarantor                         2
Mobile_Verified                   2
Email_Verified                    2
dtype: int64

In [47]:
drop_cols = [
    'Institutional_Relationships',
    'Religion',
    'City'
]

df.drop(columns=drop_cols, inplace=True)

In [48]:
for col in df.select_dtypes(include='object').columns:
    print(f"\n{col}")
    print(df[col].nunique())

Gender
3

Married
2

Education
2

Employment_Status
4

Property_Area
3

Loan_Status
2

Purpose_of_Loan
7

Guarantor
2

Co-signer_Relationship
6

Organization_Type
5

Region_Branch
7

Mobile_Verified
2

Email_Verified
2

Customer_Sentiment
3

State
10

Occupation
18

C:\Users\sujal\AppData\Local\Temp\ipykernel_15580\2078998271.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [51]:
numeric_cols = [
    'Applicant_Income',
    'Loan_Amount',
    'Asset_Value',
    'Debt_to_Income_Ratio',
    'Annual_Household_Income'
]

for col in numeric_cols:
    print(col)
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print("Outliers:", outliers)

Applicant_Income
Outliers: 3
Loan_Amount
Outliers: 61
Asset_Value
Outliers: 20
Debt_to_Income_Ratio
Outliers: 118
Annual_Household_Income
Outliers: 30

In [52]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Employment_Status',
       'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount',
       'Loan_Term_Months', 'Credit_History', 'Property_Area', 'Age',
       'Loan_Status', 'CIBIL_Score', 'Annual_Household_Income',
       'Debt_to_Income_Ratio', 'Purpose_of_Loan', 'Existing_EMIs',
       'Number_of_Previous_Loans', 'Default_History_Count',
       'Employment_Length_Years', 'Asset_Value', 'Guarantor',
       'Co-signer_Relationship', 'Monthly_Expense', 'Organization_Type',
       'Region_Branch', 'Mobile_Verified', 'Email_Verified',
       'Loan_to_Annual_Income', 'Customer_Sentiment', 'State', 'Occupation'],
      dtype='str')

In [53]:
df.head()

,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Property_Area,Age,Loan_Status,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Purpose_of_Loan,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Guarantor,Co-signer_Relationship,Monthly_Expense,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Loan_to_Annual_Income,Customer_Sentiment,State,Occupation
0,Male,No,2,Graduate,Salaried,56976,0,8031545,360,1,Urban,36,Approved,699,683712,0.098,Home,5610,0,0,1,744861,No,Friend,30391,Public,KOL-004,No,Yes,11.747,Positive,Delhi,Farmer
1,Male,No,0,Graduate,Unemployed,1856,0,899361,240,1,Rural,42,Rejected,707,22272,4.939,Business,9166,1,0,0,0,No,Sibling,1856,Startup,DEL-001,No,Yes,40.381,Negative,Punjab,Civil Engineer
2,Female,Yes,0,Graduate,Salaried,64553,0,2387748,60,1,Rural,38,Approved,641,774636,0.000,Business,0,2,0,1,2913766,No,Unknown,24557,Private,BLR-003,Yes,Yes,3.082,Positive,Maharashtra,Medical Representative
3,Male,No,0,Graduate,Salaried,88450,0,658856,12,1,Semiurban,32,Approved,677,1061400,0.301,Personal,26613,1,0,3,3488244,No,Friend,36750,Startup,KOL-004,Yes,Yes,0.621,Negative,Gujarat,Marketing Executive
4,Male,Yes,3,Graduate,Self-Employed,9539,0,198671,36,0,Semiurban,35,Approved,594,114468,0.000,Personal,0,0,0,2,472179,No,Parent,3920,Public,BLR-003,Yes,Yes,1.736,Neutral,West Bengal,Shopkeeper